// tslint:disable: no-magic-numbers
import {TimeBuilder, TimeDeltaBuilder} from './'

describe('date test', () => {
    it('build date test', () => {
        const time1 = new TimeBuilder()
            .hour(1)
            .minute(2)
            .second(3)
            .millisecond(4)
            .microsecond(5)
            .build()
        expect(time1.hour).toBe(1)
        expect(time1.minute).toBe(2)
        expect(time1.second).toBe(3)
        expect(time1.millisecond).toBe(4)
        expect(time1.microsecond).toBe(5)
    })
    it('build dateDelta test', () => {
        const timeDelta1 = new TimeDeltaBuilder()
            .hour(1)
            .minute(2)
            .second(3)
            .millisecond(4)
            .microsecond(5)
            .build()
        expect(timeDelta1.hour).toBe(1)
        expect(timeDelta1.minute).toBe(2)
        expect(timeDelta1.second).toBe(3)
        expect(timeDelta1.millisecond).toBe(4)
        expect(timeDelta1.microsecond).toBe(5)
        const timeDelta2 = new TimeDeltaBuilder().build()
        expect(timeDelta2.hour).toBe(0)
        expect(timeDelta2.minute).toBe(0)
        expect(timeDelta2.second).toBe(0)
        expect(timeDelta2.millisecond).toBe(0)
        expect(timeDelta2.microsecond).toBe(0)
    })
})
